"""Document synthesis tools — template rendering, markdown generation."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Type

from crewai.tools import BaseTool
from pydantic import BaseModel, Field


class GuideTemplateInput(BaseModel):
    """Input for GuideTemplateTool."""
    architecture_md: str = Field(..., description="Architecture analysis in markdown")
    quality_report_json: str = Field(..., description="Code quality report as JSON string")
    security_report_json: str = Field(..., description="Security report as JSON string")
    repo_name: str = Field(default="unknown", description="Repository name")
    repo_url: str = Field(default="", description="Repository URL")


class GuideTemplateTool(BaseTool):
    """Render outputs into a structured GUIDE.md template for the synthesizer agent."""

    name: str = "Guide Template Renderer"
    description: str = (
        "Combine architecture, quality, and security reports into a structured GUIDE.md template. "
        "This pre-formats the data so the Doc Synthesizer agent can focus on writing quality content."
    )
    args_schema: Type[BaseModel] = GuideTemplateInput

    def _run(
        self,
        architecture_md: str,
        quality_report_json: str,
        security_report_json: str,
        repo_name: str = "unknown",
        repo_url: str = "",
    ) -> str:
        """Render the guide template and return markdown."""
        # Parse reports
        quality = self._safe_json(quality_report_json)
        security = self._safe_json(security_report_json)

        sections: list[str] = []

        # Header
        sections.append(f"# {repo_name} — Developer Guide")
        sections.append("")
        sections.append(f"> Auto-generated by **RepoInsight** on {datetime.now().strftime('%Y-%m-%d')}")
        if repo_url:
            sections.append(f"> Source: [{repo_url}]({repo_url})")
        sections.append("")
        sections.append("---")
        sections.append("")

        # Quick stats
        sections.append("## Quick Stats")
        sections.append("")
        q_score = quality.get("overall_score", "N/A")
        s_risk = security.get("risk_level", "N/A")
        sections.append(f"| Metric | Value |")
        sections.append(f"|--------|-------|")
        sections.append(f"| Code Quality Score | {q_score}/10 |")
        sections.append(f"| Security Risk Level | {s_risk} |")
        sections.append("")

        # Architecture
        sections.append("## Architecture")
        sections.append("")
        sections.append(architecture_md if architecture_md else "_No architecture analysis available._")
        sections.append("")

        # Module navigation
        sections.append("## Module Navigation")
        sections.append("")
        sections.append("_Fill in with module descriptions from the architecture analysis._")
        sections.append("")

        # Development setup
        sections.append("## Development Setup")
        sections.append("")
        sections.append("```bash")
        sections.append("# Clone the repository")
        if repo_url:
            sections.append(f"git clone {repo_url}")
        sections.append(f"cd {repo_name}")
        sections.append("")
        sections.append("# Install dependencies (inferred from project structure)")
        sections.append("pip install -e .")
        sections.append("```")
        sections.append("")

        # Code quality
        sections.append("## Code Quality")
        sections.append("")
        if quality:
            sections.append(f"**Overall Score**: {q_score}/10")
            sections.append("")
            issues = quality.get("issues", [])
            if issues:
                sections.append("### Top Issues")
                sections.append("")
                sections.append("| Severity | Category | File | Description | Suggestion |")
                sections.append("|----------|----------|------|-------------|------------|")
                for issue in issues[:10]:
                    sev = issue.get("severity", "?")
                    cat = issue.get("category", "?")
                    file = issue.get("file", "?")
                    desc = issue.get("description", "")[:80]
                    sug = issue.get("suggestion", "")[:80]
                    sections.append(f"| {sev} | {cat} | {file} | {desc} | {sug} |")
                sections.append("")
            strengths = quality.get("strengths", [])
            if strengths:
                sections.append("### Strengths")
                sections.append("")
                for s in strengths:
                    sections.append(f"- ✅ {s}")
                sections.append("")
        else:
            sections.append("_No quality report available._")
            sections.append("")

        # Security
        sections.append("## Security")
        sections.append("")
        if security:
            sections.append(f"**Risk Level**: `{s_risk.upper()}`")
            sections.append("")
            vulns = security.get("vulnerabilities", [])
            if vulns:
                sections.append("### Vulnerabilities Found")
                sections.append("")
                for v in vulns[:10]:
                    vid = v.get("id", "?")
                    sev = v.get("severity", "?")
                    desc = v.get("description", "")[:100]
                    rem = v.get("remediation", "")[:100]
                    sections.append(f"- **{vid}** [{sev}] — {desc}")
                    sections.append(f"  > Fix: {rem}")
                sections.append("")
            recs = security.get("recommendations", [])
            if recs:
                sections.append("### Recommendations")
                sections.append("")
                for r in recs:
                    sections.append(f"- 🔒 {r}")
                sections.append("")
        else:
            sections.append("_No security report available._")
            sections.append("")

        # Contributing
        sections.append("## Contributing")
        sections.append("")
        sections.append("_Generated from project conventions found during analysis._")
        sections.append("")
        sections.append("1. Fork the repository")
        sections.append("2. Create a feature branch (`git checkout -b feature/your-feature`)")
        sections.append("3. Write tests for your changes")
        sections.append("4. Run tests (`pytest`)")
        sections.append("5. Submit a Pull Request")
        sections.append("")

        # Footer
        sections.append("---")
        sections.append("")
        sections.append("*Generated by [RepoInsight](https://github.com) — Multi-Agent Repository Analysis Platform*")

        return "\n".join(sections)

    @staticmethod
    def _safe_json(raw: str) -> dict:
        """Parse JSON safely, return empty dict on failure."""
        try:
            return json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            return {}


class SaveOutputInput(BaseModel):
    """Input for SaveOutputTool."""
    content: str = Field(..., description="Content to save")
    filename: str = Field(default="GUIDE.md", description="Output filename")


class SaveOutputTool(BaseTool):
    """Save analysis output to disk."""

    name: str = "Save Output Tool"
    description: str = "Save the generated content to a file on disk"
    args_schema: Type[BaseModel] = SaveOutputInput

    def _run(self, content: str, filename: str = "GUIDE.md") -> str:
        """Save content to file and return the path."""
        output_path = Path.cwd() / filename
        output_path.write_text(content, encoding="utf-8")
        return f"Saved to {output_path.absolute()}"
